### ISSUE TITLE
Unable to use the package

### ISSUE THREAD

**Issue by ShreyAmbesh** [Diizzayy/nuxt-graphql-client#242] opened 2022-11-03 07:48 UTC
I am getting an error 
```
ERROR  Cannot start nuxt:  The requested module '@graphql-codegen/plugin-helpers' does not provide an export named 'DetailedError'                                                         12:03:52

  import { DetailedError, createNoopProfiler } from '@graphql-codegen/plugin-helpers';
  ^^^^^^^^^^^^^
  SyntaxError: The requested module '@graphql-codegen/plugin-helpers' does not provide an export named 'DetailedError'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
  at async normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:476:26)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:455:41)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1606:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
  at async Object.invoke (node_modules/nuxi/dist/chunks/dev.mjs:6828:5)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```
I guess it might be because of the recent update to the [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator) more specifically because of [this PR](https://github.com/dotansimha/graphql-code-generator/pull/8525) where they have removed the `DetailedError`

**Comment by Diizzayy** [comment] 2022-11-03 14:51
@ShreyAmbesh @boboldehampsink Temporary fix:

Add the following to your `package.json` file to pin the pertinent dependencies.

#### For NPM

```json
  "overrides": {
    "@graphql-codegen/cli": "2.13.4",
    "@graphql-codegen/core": "2.6.2",
    "@graphql-codegen/plugin-helpers": "2.7.1"
  }
```

#### For Yarn / Pnpm

```json
  "resolutions": {
    "@graphql-codegen/cli": "2.13.4",
    "@graphql-codegen/core": "2.6.2",
    "@graphql-codegen/plugin-helpers": "2.7.1"
  }
```

**Comment by ShreyAmbesh** [comment] 2022-11-04 07:26
@Diizzayy thanks for the temporary fix. I can confirm it works.

**Comment by talaxasy** [comment] 2022-11-13 01:42
@Diizzayy's method No. 1 doesn't work for me, and the second didn't try

**Comment by daniluk4000** [comment] 2022-11-13 09:18
@talaxasy Second works like a charm

**Comment by stlbucket** [comment] 2022-11-16 17:41
https://github.com/npm/cli/issues/5850

just dropping this issue here - i was able to get the DefaultError problem fixed, then it broke again when i re-installed.

even with overrides, npm install is giving me the 2.7.1 version for @graphql-codegen/plugin-helpers.  the others are ok, though...

maddening

**Comment by Diizzayy** [comment] 2022-11-16 17:49
> maddening

@stlbucket Indeed, this is quite an annoying bug caused by important upstream dependencies that we haven't been able to get around. As a temporary workaround I might resort to publishing a patched version of the dep to be used solely by this nuxt module that averts this issue.

**Comment by Diizzayy** [comment] 2022-11-16 19:20
@stlbucket release is on the way!

**Comment by Diizzayy** [comment] 2022-11-16 19:21
@talaxasy release is on the way!

**Comment by stuible** [comment] 2022-11-16 20:58
I had to blow away my package-lock.json but this update installs and runs smoothly without the need for overrides.  Thanks so much for your work on this package!

**Comment by Diizzayy** [comment] 2022-11-16 20:59
@stuible Okay perfect! I'm happy to hear it's working properly for you.

**Comment by stlbucket** [comment] 2022-11-17 00:02
@Diizzayy - i will be trying this soon - fyi i had been on rc13, then woke up this morning so have rebuilt on 3.0

nuxt-graphql-client is showing as 0.2.12 in my package.json - above you said 0.2.11?

my next step will be incorporating pinia, which is where i actually encountered the problem previously

**Comment by stlbucket** [comment] 2022-11-17 00:06
https://github.com/vuejs/pinia/issues/853

pinia requires --legacy-peer-deps

due to the same bug, i believe?

**Comment by Diizzayy** [comment] 2022-11-17 00:09
@stlbucket Pinia should work fine alongside this module, Let me know what if any issue your run into and I'll have a look into it

**Comment by stlbucket** [comment] 2022-11-17 00:15
@Diizzayy - seems to have worked for now

**Comment by talaxasy** [comment] 2022-11-17 13:33
> @ShreyAmbesh @stlbucket @talaxasy @stuible version `0.2.11` has been released with the aforementioned patch. Looking forward to hearing your feedback.

yeah, works

**Comment by Diizzayy** [comment] 2022-11-30 16:55
Closing, this was recently resolved upstream as per dotansimha/graphql-code-generator#8590

**Closed by Diizzayy** 2022-11-30 16:55 UTC
Labels: bug
